SportsStore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models
{
    public class Cart
    {
        private List<CartItem> CartContents = new List<CartItem>();

        public virtual IEnumerable<CartItem> Contents => CartContents;

        public virtual void AddItem(Product product, int quantity)
        {   
            //check to see if item already exists in cartcontents; byt checking if any match with one sent from route and ave to item
            CartItem item = CartContents.Where(p => p.Product.ProductID == product.ProductID).FirstOrDefault();

            if (item == null)
            {
                CartContents.Add(new CartItem{Product = product, Quantity = quantity}
                );
            }
            else
            {
                item.Quantity += quantity;
            }
        }

        public virtual void RemoveItem(Product product)
        {
            CartContents.RemoveAll(i => i.Product.ProductID == product.ProductID);
        }

        public virtual decimal ComputeTotal()
        {
            return CartContents.Sum(ci => ci.Product.Price * ci.Quantity);
        }

        public virtual void ClearCart()
        {
            CartContents.Clear();
        }
    }

    public class CartItem
    {
        public int CartItemID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

SportsStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class CartController: Controller
    {
        private IProductRepository _respository;
        private Cart _cart;
        
        //repo amd carServce objects are auto created according to config file when the MVC calls this controller ctor
        public CartController(IProductRepository respository, Cart cartService)
        {
            _respository = respository;
            _cart = cartService;
        }


        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel {
                Cart=_cart, ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {   //using where below returns I querable object, whereas FirstOrDefaul rtns a single item
            Product product = _respository.Products.FirstOrDefault(p => p.ProductID == productId);
            //*****provided by SessionCart service, no longer needed****
//        **var cart = GetCart();
            if (product != null)
            {
                _cart.AddItem(product, 1);
            }

//          **SaveCart(cart);
            return RedirectToAction("Index", new{returnUrl});
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            var product = _respository.Products.FirstOrDefault(p => p.ProductID == productId);
//          **var cart = GetCart();
            if (product != null)
            {
                _cart.RemoveItem(product);
            }

//          **SaveCart(cart);
            return RedirectToAction("Index", new{returnUrl});
        }



   //**removed code pertaining to session storage and created a new SessionCart class (service) which inherits Cart class and adds session finctionality
//        private Cart GetCart()
//        {
//            var cart = HttpContext.Session.GetJobj<Cart>("Cart") ?? new Cart();
//            return cart;
//        }
//        private void SaveCart(Cart cart)
//        {
//            HttpContext.Session.SetJobj("Cart", cart);
//        }
    }
}

SportsStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Checkout()
        {
            return View(new Order());
        }
    }
}

SportsStore/Views/Cart/Index.cshtml
@*view that renderders items in the shopping cart, invoked by the cart controller*@

@model CartIndexViewModel
<h2>Your Cart</h2>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Quantity</th>
        <th>Item</th>
        <th class="text-right">Price</th>
        <th class="text-right">Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Cart.Contents)
    {
        <tr>
            <td class="text-center">@item.Quantity</td>
            <td class="text-left">@item.Product.Name</td>
            <td class="text-right">@item.Product.Price.ToString("c")</td>
            <td class="text-right">@((item.Quantity * item.Product.Price).ToString("c"))</td>
            <td class="text-center">
                <form asp-action="RemoveFromCart" asp-controller="Cart" method="post">
                    <input type="hidden" name="productId" value="@item.Product.ProductID" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove 
                    </button>
                </form>

            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Total:</td>
        <td class="text-right">@Model.Cart.ComputeTotal().ToString("c")</td>
    </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">Checkout</a>
</div>