SportsStore/Components/CartSummaryViewComponent.cs
//model for cart wideget and subtotal on top right of page
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }

}

SportsStore/Components/NavigationMenuViewComponent.cs
//Navigation component: logic that queries all the available categories from the repository and sends them to the defualt view for the cartcontroller
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent:ViewComponent
    {
        private  IProductRepository _repository;

        public NavigationMenuViewComponent(IProductRepository repository)
        {
            _repository = repository;
        }
// enter into html using @await Component.InvokeAsync("NavigationMenu")
//this builds the "defult" view (html component) in the components folder and plugs it in whereever the above method is called, typically on Layout

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_repository.Products.Select(x => x.Category).Distinct().OrderBy(x => x));
        }

    }
}

SportsStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class CartController: Controller
    {
        private IProductRepository _respository;
        private Cart _cart;
        
        //repo amd carServce objects are auto created according to config file when the MVC calls this controller ctor
        public CartController(IProductRepository respository, Cart cartService)
        {
            _respository = respository;
            _cart = cartService;
        }


        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel {
                Cart=_cart, ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {   //using where below returns I querable object, whereas FirstOrDefaul rtns a single item
            Product product = _respository.Products.FirstOrDefault(p => p.ProductID == productId);
            //*****provided by SessionCart service, no longer needed****
//        **var cart = GetCart();
            if (product != null)
            {
                _cart.AddItem(product, 1);
            }

//          **SaveCart(cart);
            return RedirectToAction("Index", new{returnUrl});
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            var product = _respository.Products.FirstOrDefault(p => p.ProductID == productId);
//          **var cart = GetCart();
            if (product != null)
            {
                _cart.RemoveItem(product);
            }

//          **SaveCart(cart);
            return RedirectToAction("Index", new{returnUrl});
        }



   //**removed code pertaining to session storage and created a new SessionCart class (service) which inherits Cart class and adds session finctionality
//        private Cart GetCart()
//        {
//            var cart = HttpContext.Session.GetJobj<Cart>("Cart") ?? new Cart();
//            return cart;
//        }
//        private void SaveCart(Cart cart)
//        {
//            HttpContext.Session.SetJobj("Cart", cart);
//        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@model Product
@*//html partial to display a single product, then used in for each loop on main html page to render for each product*@
@*inject into html using @Html.Partial("ProductSummary", p)*@
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">

        <h4>@Model.Name   <span class="badge badge-pill badge-primary" style="float:right"><small >@Model.Price.ToString("C")</small></span></h4>
        <form asp-action="AddToCart" asp-controller="Cart" method="post">
            <input type="hidden" asp-for="ProductID" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.GetEncodedPathAndQuery()" />
            <span class="card-text p-1">
                @Model.Description
                        <button type="submit" class="btn btn-success btn-sm" style="float:right" >Add to Cart </button>
                    </span>
        </form>

    </div>
    
</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportStore</title>
    <link asp-href-include="/lib/bootstrap/dist/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid*" rel="stylesheet" />
    <link asp-href-include="/lib/fontawesome/css/*.css" rel="stylesheet" />
</head>
<body>
<div class="navbar navbar-dark bg-dark" role="navigation">
    <a class="navbar-brand" href="#">Sports Store</a>
    <div class="col-4 text-right">
        @await Component.InvokeAsync("CartSummary")
    </div>
</div>
<div class="row m-1 p-1">
    <div id="categories" class="col-3">
        @await Component.InvokeAsync("NavigationMenu")
    </div>
    <div class="col-9">@RenderBody()</div>
</div>
    <div>
        
    </div>
</body>
</html>